# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.
{ 
  config, 
  lib, 
  pkgs, 
  modulesPath, 
  ... 
}: {
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" "sdhci_pci" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/mapper/luks-bcebf0a1-8f38-416c-b522-4c3324258799";
      fsType = "btrfs";
      options = [ "subvol=@" ];
    };

  boot.initrd.luks.devices."luks-bcebf0a1-8f38-416c-b522-4c3324258799".device = "/dev/disk/by-uuid/bcebf0a1-8f38-416c-b522-4c3324258799";

  fileSystems."/home" =
    { device = "/dev/mapper/luks-bcebf0a1-8f38-416c-b522-4c3324258799";
      fsType = "btrfs";
      options = [ "subvol=@home" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/2A75-6A77";
      fsType = "vfat";
      options = [ "fmask=0077" "dmask=0077" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
